tuphuong/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :clients
  resources :rooms do
    resources :rents
  end
  resources :prices
  resources :discounts
  resources :roles
  

  root 'home#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/report' => 'rents#report'

end

tuphuong/app/models/role.rb
class Role < ActiveRecord::Base
    has_many :users

        validates :name, :presence => true, 
                     :uniqueness => true,
                     format: { with: /\A[a-z]+\z/,
                                   message: "only allows lowercase letters" }

    validates :description, :presence => true

    def name_with_initial
        "#{description}"
    end
end

tuphuong/app/controllers/roles_controller.rb
class RolesController < ApplicationController

    before_filter :authorize
    before_filter :adminAuthorize

    def index
        @roles = Role.all
    end

    def show
        @role = Role.find(params[:id])
    end

    def new
        @role = Role.new
    end

    def edit
      @role = Role.find(params[:id])
    end

    def create       
        @role = Role.create(role_params)

        if @role.save
            redirect_to roles_path
        else
            render 'new'
        end
    end

    def update
      @role = Role.find(params[:id])
     
      if @role.update(role_params)
        redirect_to @role
      else
        render 'edit'
      end
    end

    def destroy
      @role = Role.find(params[:id])
      @role.destroy
     
      redirect_to roles_path
    end

    private
      def role_params
        params.require(:role).permit(:name, :description, :count)
      end
end

tuphuong/app/helpers/roles_helper.rb
module RolesHelper
end

tuphuong/app/views/roles/_form.html.erb
<%= form_for @role, html: {class: "col s12"} do |f| %>
  <div class="row">
    <% if @role.errors.any? %>
      <div id="error_explanation">
        <h5>
          <%= pluralize(@role.errors.count, "error") %> prohibited
          this role from being saved:
        </h5>
        <ul class="collection">
          <% @role.errors.full_messages.each do |msg| %>
            <li class="collection-item red-text text-darken-1"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="input-field col s12">
      <i class="mdi-action-account-circle prefix"></i>
      <%= f.label :name, 'Tên', :class => 'active' %>
      <%= f.text_field :name, :class => 'validate' %>
    </div>

    <div class="input-field col s12">
      <i class="mdi-action-description prefix"></i>
      <%= f.label :description, 'Mô tả', :class => 'active' %>
      <%= f.text_field :description, :class => 'validate' %>
    </div>


    <div class="input-field col s12 center-align">
      <%= f.submit "Hoàn tất", :class => 'waves-effect btn w150' %>
    </div>
  </div>
<% end %>

tuphuong/app/views/roles/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Sửa roles #<%= @role.id %></h2>
            <div class="row">
                <%= render 'form' %>
            </div>
            <a href="<%= roles_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/roles/index.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Danh sách role</h2>
        <a href="<%= new_role_path %>" class="btn-floating btn-large waves-effect waves-light red tooltipped" data-position="top" data-delay="10" data-tooltip="Thêm role">
            <i class="mdi-hardware-security"></i>
        </a>
        <table>
          <thead>
            <tr>
              <th data-field="role_name">Tên</th>
              <th data-field="role_description">Mô tả</th>
              <th data-field="action">Thao tác</th>
            </tr>
          </thead>
          <tbody>
            <% @roles.each do |role| %>
                <tr>
                  <td><%= role.name %></td>
                  <td><%= role.description %></td>
                  <td>
                    <%= link_to 'Xem', role_path(role) %> /
                    <%= link_to 'Sửa', edit_role_path(role) %> /
                    <%= link_to 'Xóa', role_path(role),
                        method: :delete,
                        data: { confirm: 'Bạn có chắc không?' } %>
                  </td>
                </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

tuphuong/app/views/roles/new.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Thêm roles</h2>
            <div class="row">
                <%= render 'form' %>
            </div>
            <a href="<%= roles_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/roles/show.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Role #<%= @role.id %></h2>
            <table>
              <thead>
                <tr>
                  <th data-field="role_name">Tên</th>
                  <th data-field="role_description">Mô tả</th>
                  <th data-field="action">Thao tác</th>
                </tr>
              </thead>
              <tbody>
                  <tr>
                    <td><%= @role.name %></td>
                    <td><%= @role.description %></td>
                    <td>
                      <%= link_to 'Xem', role_path(@role) %> /
                      <%= link_to 'Sửa', edit_role_path(@role) %> /
                      <%= link_to 'Xóa', role_path(@role),
                          method: :delete,
                          data: { confirm: 'Bạn có chắc không?' } %>
                    </td>
                  </tr>
              </tbody>
            </table>
            <a href="<%= roles_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>