tuphuong/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :clients
  resources :rooms do
    resources :rents
  end
  resources :prices
  resources :discounts
  resources :roles
  

  root 'home#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/report' => 'rents#report'

end

tuphuong/app/models/rent.rb
class Rent < ActiveRecord::Base

  acts_as_xlsx

	belongs_to :rooms
	
    # validates :user_id, :room_id, :price_id, :client_id , :start_at, :end_at, :tmp_price, :total_price, presence: true
    #validates :rent_type , presence: true

    def vn_type
        if rent_type == '1h' 
    		  vn_type = 'Theo giờ' 
        elsif rent_type == 'day' 
         	vn_type = 'Ngày'
      	else 
        	vn_type =	'Qua đêm' 
      	end 
    end
    
    def client
      if client_id and @client = Client.find(client_id)
        client = @client
      end
    end

    def room
      if room_id and @room = Room.find(room_id)
        room = @room
      end
    end

    def user
      if user_id and @user = User.find(user_id)
        user = @user
      end
    end
end

tuphuong/app/controllers/rents_controller.rb
class RentsController < ApplicationController
	before_filter :authorize
	def new
		@room = Room.find(params[:room_id])
		@rent = @room.rents.new
	end
	
	def show
    	@rent = Rent.find(params[:id])
  	end

	def index
    	@rents = Rent.all
  	end

  	def report
  		@users = User.all

  		@get_date_type = params[:get_date_type]
  		@get_user_id = params[:get_user_id]
  		@where = '';
  		if @get_user_id and @get_user_id.to_i > 0
  			@where =  'rents.user_id = ' + @get_user_id;
  		end
  		if @get_date_type === 'today'
  			@where = ((@where != '')? (@where + ' AND ') :'') + "DATE(rents.start_at)  = '" +  Date.today.to_s + "'"
  		elsif @get_date_type == 'month'
  			@where = ((@where != '')? (@where + ' AND ') :'') + " rents.start_at  >= '" +  Time.now.beginning_of_month.to_s + "' AND rents.start_at  <= '" +  Time.now.end_of_month.to_s + "'"
  		end
  		@reports = Rent.where(@where).order('start_at DESC').paginate(page: params[:page], per_page: 20)

    	#@reports = Rent.select('rents.*,c.*').
    	#	joins(
    	#	'LEFT JOIN rooms AS r ON r.id = rents.room_id',
    	#	'LEFT JOIN users AS u ON u.id = rents.user_id',
    	#	'LEFT JOIN clients AS c ON c.id = rents.client_id',
    	#	).where(@where).order('start_at DESC').paginate(page: params[:page], per_page: 2)

    	#respond_to do | format |  
		 # format.html # report.html.erb
		 # format.xlsx {
		 # 	render xlsx: "report", filename: "report.xlsx"  
		 # }  
		#end
  	end
	
	def edit
		@room = Room.find(params[:room_id])
  		@rent = @room.rents.find(params[:id])
	end

	def create
		@room = Room.find(params[:room_id])
		if params[:format] == 'json'
			@rent = @room.rents.new()
	  		@price = Price.where(:price_type => @room.room_type, :time => params[:rent_type]).first

			@rent.start_at = Time.now.to_datetime
			@rent.rent_type = params[:rent_type]
			@rent.user_id = current_user.id
		  	if @price
		  		@rent.price_id = @price.id
		  	end
			if @rent.save
				@room.active_rent_id = @rent.id
				@room.status = 'full'
				@room.save
				render :json => @rent , :status => 200
			else
				render :json => @rent , :status => 0
	    	end
		else
		  	@rent = @room.rents.create(rent_params)
	  		@price = Price.where(:price_type => @room.room_type, :time => params[:rent][:rent_type]).first

			@rent.start_at = Time.now.to_datetime
			@rent.user_id = current_user.id
		  	if @price
		  		@rent.price_id = @price.id
		  	end
			if @rent.save
				@room.active_rent_id = @rent.id
				@room.status = 'full'
				@room.save
				flash[:notice] = "Đặt thành công"
				# render plain: @rent.inspect
				redirect_to '/'
			else
				# render plain: params.inspect
	    		render 'new'
	    	end
	    end
	end
	def update
	  @room = Room.find(params[:room_id])
	  @rent = @room.rents.find(params[:id])
	  @price = Price.find(@rent.price_id)

	  if @rent.rent_type == '1h'
	  	@price_more = Price.where(:price_type => @room.room_type, :time => '1h+').first

	  	@hours_diff = (Time.parse(DateTime.now.to_s) - Time.parse(@rent.start_at.to_s))/3600
	  	@total_hours = (@hours_diff + 0.167).round
	  	if @total_hours > 1
	  		@rent.total_hours = @total_hours
	  		@rent.tmp_price = @price.price_value + (@total_hours - 1) * @price_more.price_value
	  	else
	  		@rent.total_hours = 1
	  		@rent.tmp_price = @price.price_value 
	  	end
	  	@rent.total_price = @rent.tmp_price
	  else
		@rent.tmp_price = @price.price_value	  		
		@rent.total_price = @price.price_value
	  end
	  @rent.end_at = Time.now.to_datetime

	  if @rent.update(rent_params)
	  	#@room.active_rent_id = 0
		@room.status = 'cleaning'
		@room.save
		flash[:notice] = "Thành công"
		if params[:format] == 'json'
			render :json => @rent , :status => 200
    	else
	    	redirect_to '/'
	    end
	  else
	    render 'edit'
	  end
	end

	def destroy
		@rent = Rent.find(params[:id])
	  	@rent.destroy
	 
	  	redirect_to '/rooms/1/rents'
	end

	private
	  	def rent_params
	   		params.require(:rent).permit(:user_id, :client_id, :room_id, :start_at, :end_at, :tmp_price, :total_price, :rent_type)
	  	end
end

tuphuong/app/helpers/rents_helper.rb
module RentsHelper
end

tuphuong/app/views/rents/_form.html.erb
<%= form_for ([@room, @room.rents.build]), html: {class: "col s12"} do |f| %>
  <div class="row">
    <% if @rent.errors.any? %>
      <div id="error_explanation">
        <h5>
          <%= pluralize(@rent.errors.count, "error") %> prohibited
          this rent from being saved:
        </h5>
        <ul class="collection">
          <% @rent.errors.full_messages.each do |msg| %>
            <li class="collection-item red-text text-darken-1"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="input-field col s12 select-custom">
      <i class="mdi-action-verified-user prefix"></i>
      <%= f.select :rent_type, [['Chọn cách thuê', ''], ['Theo giờ', '1h'], ['Qua đêm', 'overnight']] %>
    </div>

    <div class="input-field col s12 select-custom">
      <i class="mdi-action-verified-user prefix"></i>
      <%= collection_select(:rent, :client_id, Client.all, :id, :name, {:prompt => 'Chọn khách hàng'}) %>
    </div>

    <div class="input-field col s12 select-custom datetime_select">
      <i class="prefix"></i>
      <%= f.datetime_select(:start_at, :default => { :hour => 23, :minute => 59 }) %>
    </div>

    <input type="hidden" name="rent[user_id]" value="0">
    <input type="hidden" name="rent[price_id]" value="1">
    <input type="hidden" name="rent[end_at]" value="0">
    <input type="hidden" name="rent[tmp_price]" value="0">
    <input type="hidden" name="rent[total_price]" value="0">

    <div class="input-field col s12 center-align">
      <%= f.submit "Hoàn tất", :class => 'waves-effect btn w150' %>
    </div>
  </div>
<% end %>

tuphuong/app/views/rents/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Tính tiền #<%= @room.number %></h2>
            <ul>
                <li>
                    <h4>Loại phòng : <%= @room.room_type %></h4>
                </li>
                <li>
                    <h4>Giá phòng : </h4>
                    <ul>
                        <% Price.where(:price_type => @room.room_type).all.each do |price_for_room| %>
                            <li><%= price_for_room.time %> giá :  <%= number_to_currency(price_for_room.price_value, unit: 'VND ') %></li>
                        <% end %>
                    </ul>
                </li>
                <li>
                    <h4>Thời gian vào thuê: <%= @rent.start_at %> </h4>
                </li>
                <li>
                    <h4>Kiểu thuê: 
                        <% if @rent.rent_type == '1h' %>
                            Theo giờ
                        <% else %>
                            Qua đêm
                        <% end %> 
                    </h4>
                </li>
                <li>
                    
                    <%= form_for ([@room, @rent]), html: {class: "col s12"} do |f| %>
                        <% if @rent.rent_type == '1h' %>
                            <div class="input-field col s12">
                              <%= f.label :total_hours, 'So gio thue', :class => 'active' %>
                              <%= f.text_field :total_hours, :class => 'validate', :value => 2 %>
                            </div>
                            <div class="input-field col s12">
                              <i class="mdi-editor-attach-money prefix"></i>
                              <%= f.label :total_price, 'Tổng tiền :  ', :class => 'active' %>
                              <%= f.text_field :total_price, :class => 'validate', :value => '350.000' %>
                            </div>
                        <% else %>
                            <h4>Tổng tiền : VND 400.000</h4>
                        <% end %> 
                        <input type="hidden" name="rent[user_id]" value="<%= @rent.user_id %>">
                        <input type="hidden" name="rent[price_id]" value="<%= @rent.price_id %>">
                        <input type="hidden" name="rent[end_at]" value="<%= @rent.end_at %>">
                        <input type="hidden" name="rent[tmp_price]" value="<%= @rent.tmp_price %>">
                        <input type="hidden" name="rent[total_price]" value="<%= @rent.total_price %>">

                        <div class="input-field col s12 center-align">
                          <%= f.submit "Hoàn tất", :class => 'waves-effect btn w150' %>
                        </div>
                    <% end %>
                </li>
            </ul>
            <div class="row">
                

            </div>
            <a href="/" class="waves-effect waves-light btn grey darken-3">
              Quay lại
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/rents/index.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Lịch sử thuê phòng</h2>
        <a href="<%= new_room_rent_path %>" class="btn-floating btn-large waves-effect waves-light red">
            <i class="mdi-social-person-add"></i>
        </a>
        <table>
            <thead>
              <tr>
                  <th data-field="room_id">Số phòng</th>
                  <th data-field="user_name">Nhân viên</th>
                  <th data-field="client_id">Khách hàng</th>
                  <th data-field="start_at">Giờ vào</th>
                  <th data-field="end_at">Giờ ra</th>
                  <th data-field="tmp_price">Giá tạm tính</th>
                  <th data-field="total_price">Giá thanh toán</th>
                  <th data-field="action">Thao tác</th>
              </tr>
            </thead>
            <tbody>
              <% @rents.each do |rent| %>
                <tr>
                  <td><%= rent.room.number %></td>
                  <td><%= (rent.user)? rent.user.fullname : '--' %></td>
                  <td><%= (rent.client)? rent.client.name : '--' %></td>
                  <td><%= rent.start_at %></td>
                  <td><%= rent.end_at %></td>
                  <td><%= rent.tmp_price %></td>
                  <td><%= rent.total_price %></td>
                  <td class="col s3">
                        <%= link_to 'Xóa', [rent.room,rent],
                            method: :delete,
                            data: { confirm: 'Bạn có chắc không?' } %>
                      </td>
                </tr>
              <% end %>
            </tbody>
        </table>
        <div class="divider custom-divider"></div>
    </div>
</div>

tuphuong/app/views/rents/new.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Cho thuê phòng #<%= @room.number %></h2>
            <ul>
                <li>
                    <h4>Loại phòng : <%= @room.room_type %></h4>
                </li>
                <li>
                    <h4>Giá phòng : </h4>
                    <ul>
                        <% Price.where(:price_type => @room.room_type).all.each do |price_for_room| %>
                            <li><%= price_for_room.time %> giá :  <%= number_to_currency(price_for_room.price_value, unit: 'VND ') %></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
            <div class="row">
                <%= render 'form' %>
            </div>
            <a href="/" class="waves-effect waves-light btn grey darken-3">
              Quay lại
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/rents/report.html.erb
<% if current_user and current_user.role.name === 'admin' %>
  <div class="row">
      <div class="col s12">
          <h2 class="center-align">Report</h2>
          <!-- <%= link_to 'Link download report', url_for(:format=>"xlsx") %> -->
          <div class="row">
              <form method="GET" action="<%= report_path %>">
                  <select class="left select-user mr-15" name="get_date_type">
                    <option value="" >Xem tất cả</option>
                    <option value="today" <% if @get_date_type == 'today' %> selected = 'selected' <% end %>>Xem trong ngày</option>
                    <option value="month" <% if @get_date_type == 'month' %> selected = 'selected' <% end %>>Xem trong tháng</option>
                  </select>
                  <select class="left select-user mr-15" name="get_user_id">
                    <option value="">Tất cả nhân viên</option>
                    <% @users.each do |user_tmp| %>
                      <option <% if user_tmp.id.to_i == @get_user_id.to_i %> selected = 'selected' <% end %> value="<%= user_tmp.id %>"><%= user_tmp.fullname %></option>
                    <% end %>
                  </select>
                  
                  <button type="submit" class="waves-effect btn w150">Xem</button>
              </form>
          </div>
          <table>
              <thead>
                <tr>
                    <th data-field="room_id">Số phòng</th>
                    <th data-field="user_name">Nhân viên</th>
                    <th data-field="client_id">Khách hàng</th>
                    <th data-field="p_id">Số CMND</th>
                    <th data-field="start_at">Giờ vào</th>
                    <th data-field="end_at">Giờ ra</th>
                    <th data-field="total_price">Tiền thanh toán</th>
                </tr>
              </thead>
              <tbody>
                <% @reports.each do |rent| %>
                  <tr>
                    <td><%= rent.room.number %></td>
                    <td><%= (rent.user)? rent.user.fullname : '--' %></td>
                    <td><%= (rent.client)? rent.client.name : '--' %></td>
                    <td><%= (rent.client)? rent.client.p_id : '--' %></td>
                    <td><%= (rent.start_at)? rent.start_at.strftime(" %Hh%M - %m/%d/%Y") : '' %></td>
                    <td><%= (rent.end_at)? rent.end_at.strftime(" %Hh%M - %m/%d/%Y") : '' %></td>
                    <td>
                      <%= number_to_currency(rent.total_price, precision: 0, unit: 'VND', format: "%n %u")  %>
                    </td>
                  </tr>
                <% end %>
                <tr>
                  <td colspan="6" class="right-align">Tổng cộng:</td>
                  <td>
                    <b><%= number_to_currency(@reports.sum(:total_price), precision: 0, unit: 'VND', format: "%n %u")  %></b>
                  </td>
                </tr>
              </tbody>
          </table>
          <div class="divider custom-divider"></div>
        <%= will_paginate @reports %>
      </div>
  </div>
<% else %>
  <div class="center"><h3>Ban khong co quyen xem trang nay</h3></div>
<% end %> 

tuphuong/app/views/rents/show.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Chi tiet Gia </h2>
            <table>
                <thead>
                  <tr>
                    <th data-field="time">Loai gia</th>
                    <th data-field="rent_type">Loai phong</th>
                    <th data-field="rent_value">Gia</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td><%= @rent.time %></td>
                      <td><%= @rent.rent_type %></td>
                      <td><%= number_to_currency(@rent.rent_value, unit: 'VND ') %></td>
                      <td>
                        <%= link_to 'Sửa', edit_rent_path(@rent) %> /
                        <%= link_to 'Xóa', rent_path(@rent),
                            method: :delete,
                            data: { confirm: 'Bạn có chắc không?' } %>
                      </td>
                    </tr>
                </tbody>
            </table>
            <a href="<%= room_rent_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>