tuphuong/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :clients
  resources :rooms do
    resources :rents
  end
  resources :prices
  resources :discounts
  resources :roles
  

  root 'home#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/report' => 'rents#report'

end

tuphuong/app/models/room.rb
class Room < ActiveRecord::Base
	has_many :rents
    validates :number, :room_type, :status, presence: true

    def icon_status
    	if status == 'empty'
    		display_status = 'mdi-action-done s30'
    	elsif status == 'cleaning'
    		display_status = 'mdi-av-loop s30'
    	else
    		display_status = 'mdi-alert-warning s30'
    	end
    end
    def room_class
        if status == 'empty'
            room_class = 'card room-empty teal'
        elsif status == 'cleaning' 
            room_class = 'mix card room-cleaning orange darken-1'
        else
            room_class = 'mix card room-full red darken-1'
        end
    end
end

tuphuong/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    #before_filter :authorize

	def index
    	@rooms = Room.all

    	@types = Room.uniq.pluck(:room_type)
    	@floors = Room.all.map{|f| f.number[0]}.uniq
    	@status = Room.uniq.pluck(:status)
  	end

  	def show
    	@room = Room.find(params[:id])
  	end

	def new
		@room = Room.new
	end
	
	def edit
  		@room = Room.find(params[:id])
	end

	def create
	  	@room = Room.new(room_params)
		if @room.save
			flash[:notice] = "Tạo Room thành công"
			redirect_to '/'
		else
    		render 'new'
    	end
	end

	def update
	  @room = Room.find(params[:id])

	  if params[:format] == 'json'
	  	@room.status = params[:room_status]
	  	if @room.save
	  		render :json => @room , :status => 200
	  	elsif 
	  		render :json => @room, :status => 0
  		end		
	  elsif @room.update(room_params)
	  	flash[:notice] = "Sua Room thành công"
	    redirect_to rooms_path
	  else
	    render 'edit'
	  end
	end

	def destroy
		@room = Room.find(params[:id])
	  	@room.destroy
	 
	  	redirect_to rooms_path
	end

	private
	  	def room_params
	   		params.require(:room).permit(:number, :room_type, :status)
	  	end
end

tuphuong/app/helpers/rooms_helper.rb
module RoomsHelper
end

tuphuong/app/views/rooms/_form.html.erb
<%= form_for @room, html: {class: "col s12"} do |f| %>
  <div class="row">
    <% if @room.errors.any? %>
      <div id="error_explanation">
        <h5>
          <%= pluralize(@room.errors.count, "error") %> prohibited
          this room from being saved:
        </h5>
        <ul class="collection">
          <% @room.errors.full_messages.each do |msg| %>
            <li class="collection-item red-text text-darken-1"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="input-field col s12">
      <i class="mdi-editor-format-list-numbered prefix"></i>
      <%= f.label :number, 'Số phòng', :class => 'active' %>
      <%= f.text_field :number, :class => 'validate' %>
    </div>

    <div class="input-field col s12 select-custom">
      <i class="mdi-av-recent-actors prefix"></i>
      <%= f.select :room_type, [['Chọn loại phòng', ''], ['VIP', 'vip'], ['Normal', 'normal'], ['Other', 'other']] %>
    </div>

    <div class="input-field col s12 select-custom">
      <i class="mdi-action-spellcheck prefix"></i>
      <%= f.select :status, [['Chọn trạng thái', ''], ['Empty', 'empty'], ['Full', 'full'], ['Cleaning', 'cleaning']] %>
    </div>

    <div class="input-field col s12 center-align">
      <%= f.submit "Hoàn tất", :class => 'waves-effect btn w150' %>
    </div>
  </div>
<% end %>

tuphuong/app/views/rooms/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Sửa thông tin phòng</h2>
            <div class="row">
                <%= render 'form' %>
            </div>
            <a href="<%= rooms_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/rooms/index.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Danh sách phòng</h2>
        <a href="<%= new_room_path %>" class="btn-floating btn-large waves-effect waves-light red tooltipped" data-position="top" data-delay="10" data-tooltip="Thêm phòng">
          <i class="mdi-action-store"></i>
        </a>
        <div id="filterRoom" class="filter-room">
          <table>
              <thead>
                <tr>
                  <th class="col s3" data-field="number">Số phòng</th>
                  <th class="col s3" data-field="room_type">Loại phòng</th>
                  <th class="col s3" data-field="status">Trạng Thái</th>
                  <th class="col s3" data-field="action">Thao tác</th>
                </tr>
              </thead>
              <tbody>
                <tr class="th-filter">
                  <td colspan="4">
                    <form id="formFilters" class="form-filters">
                      <fieldset class="col s3">
                        <select>
                          <option value="">Tất cả tầng</option>
                          <% @floors.each do |floor| %>
                            <option value=".floor-<%= floor %>">Tầng <%= floor %></option>
                          <% end %>
                        </select>
                      </fieldset>
                      <fieldset class="col s3">
                        <select>
                          <option value="">Tất cả</option>
                          <% @types.each do |type| %>
                            <option value=".<%= type %>"><%= type %></option>
                          <% end %>
                        </select>
                      </fieldset>
                      <fieldset class="col s3">
                        <select>
                          <option value="">Tất cả</option>
                          <% @status.each do |status| %>
                            <option value=".<%= status %>"><%= status %></option>
                          <% end %>
                        </select>
                      </fieldset>
                      <button class="waves-effect waves-light btn btn-reset" id="btnReset">
                        Hủy bộ lọc
                      </button>
                    </form>
                  </td>
                </tr>
                <% @rooms.each do |room| %>
                    <tr class="mix floor-<%= room.number[0] %> <%= room.room_type %> <%= room.status %>">
                      <td class="col s3"><%= room.number %></td>
                      <td class="col s3 capz-text"><%= room.room_type %></td>
                      <td class="col s3 capz-text"><%= room.status %></td>
                      <td class="col s3">
                        <%= link_to 'Xem', room_path(room) %> /
                        <%= link_to 'Sửa', edit_room_path(room) %> /
                        <%= link_to 'Xóa', room_path(room),
                            method: :delete,
                            data: { confirm: 'Bạn có chắc không?' } %>
                      </td>
                    </tr>
                <% end %>
              </tbody>
          </table>
        </div>
    </div>
</div>

tuphuong/app/views/rooms/new.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Thêm phòng</h2>
            <div class="row">
                <%= render 'form' %>
            </div>
            <a href="<%= rooms_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/rooms/show.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Phòng <%= @room.number %></h2>
            <table>
                <thead>
                  <tr>
                    <th data-field="number">Số phòng</th>
                    <th data-field="room_type">Loại phòng</th>
                    <th data-field="status">Trạng Thái</th>
                    <th data-field="action">Thao tác</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td><%= @room.number %></td>
                      <td class="capz-text"><%= @room.room_type %></td>
                      <td class="capz-text"><%= @room.status %></td>
                      <td>
                        <%= link_to 'Sửa', edit_room_path(@room) %> /
                        <%= link_to 'Xóa', room_path(@room),
                            method: :delete,
                            data: { confirm: 'Bạn có chắc không?' } %>
                      </td>
                    </tr>
                </tbody>
            </table>
            <a href="<%= rooms_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>