tuphuong/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :clients
  resources :rooms do
    resources :rents
  end
  resources :prices
  resources :discounts
  resources :roles
  

  root 'home#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/report' => 'rents#report'

end

tuphuong/app/models/user.rb
class User < ActiveRecord::Base

    belongs_to :role

    has_secure_password
    
    #validates_confirmation_of :password

    
end

tuphuong/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    before_filter :authorize
    before_filter :adminAuthorize
    before_filter :skip_password_attribute, only: :update

    def index
        #@users = User.joins(:role)
        @users = User.paginate(page: params[:page], per_page: 10)
    end

    def show
        @user = User.joins(:role).find(params[:id])
    end

    def new
        @user = User.new
    end

    def edit
      @user = User.find(params[:id])
    end

    def create       
        @user = User.create(user_params)

        if @user.save
            session[:user_id] = @user.id
            @user.update_attribute(:last_login_at, Time.now)
            flash[:notice] = "Tạo thành công"
            redirect_to @user
        else
            render 'new'
        end
    end

    def update
      @user = User.find(params[:id])
     
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
     
      redirect_to users_path
    end

    private
      def user_params
        params.require(:user).permit(:email, :username, :fullname, :password, :password_confirmation, :role_id)
      end

      def skip_password_attribute
        if params[:password].blank? && params[:password_confirmation].blank?
           params.except!(:password, :password_confirmation)
        end
      end
end

tuphuong/app/helpers/users_helper.rb
module UsersHelper
end

tuphuong/app/views/users/_form.html.erb
<%= form_for @user, html: {class: "col s12"} do |f| %>
  <div class="row">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h5>
          <%= pluralize(@user.errors.count, "error") %> prohibited
          this user from being saved:
        </h5>
        <ul class="collection">
          <% @user.errors.full_messages.each do |msg| %>
            <li class="collection-item red-text text-darken-1"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="input-field col s12">
      <i class="mdi-communication-email prefix"></i>
      <%= f.label :email, :class => 'active' %>
      <%= f.email_field :email, :class => 'validate' %>
    </div>

    <div class="input-field col s12">
      <i class="mdi-action-account-circle prefix"></i>
      <%= f.label :username, 'Tên đăng nhập', :class => 'active' %>
      <%= f.text_field :username, :class => 'validate' %>
    </div>

    <div class="input-field col s12">
      <i class="mdi-image-tag-faces prefix"></i>
      <%= f.label :fullname, 'Tên đầy đủ', :class => 'active' %>
      <%= f.text_field :fullname, :class => 'validate' %>
    </div>

    <div class="input-field col s12">
      <i class="mdi-action-lock-outline prefix"></i>
      <%= f.label :password, 'Mật khẩu', :class => 'active' %>
      <%= f.password_field :password, :class => 'validate' %>
    </div>

    <div class="input-field col s12">
      <i class="mdi-action-lock prefix"></i>
      <%= f.label :password_confirmation, 'Nhập lại mật khẩu', :class => 'active' %>
      <%= f.password_field :password_confirmation, :class => 'validate' %>
    </div>

    <div class="input-field col s12 select-custom">
      <i class="mdi-action-verified-user prefix"></i>
      <%= collection_select(:user, :role_id, Role.all, :id, :name_with_initial, {:prompt => 'Chọn role'}) %>
    </div>
   
    <div class="input-field col s12 center-align">
      <%= f.submit "Hoàn tất", :class => 'waves-effect btn w150' %>
    </div>
  </div>
<% end %>

tuphuong/app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Chỉnh sửa #<%= @user.id %></h2>
            <div class="row">
              <div class="col s12">
                <div class="card-panel orange darken-1">
                  <span class="white-text">
                      Bạn có thể không cần cập nhật mật khẩu!
                  </span>
                </div>
              </div>
            </div>
            <div class="row">
                <%= render 'form' %>
            </div>
            <a href="<%= users_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/users/index.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Danh sách người dùng</h2>
        <a href="<%= new_user_path %>" class="btn-floating btn-large waves-effect waves-light red tooltipped" data-position="top" data-delay="10" data-tooltip="Thêm người dùng">
            <i class="mdi-social-person-add"></i>
        </a>
        <table>
            <thead>
              <tr>
                  <th data-field="id">ID</th>
                  <th data-field="email">Email</th>
                  <th data-field="username">Tên đăng nhập</th>
                  <th data-field="fullname">Tên đầy đủ</th>
                  <th data-field="role">Role</th>
                  <th data-field="action">Thao tác</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.id %></td>
                  <td><%= user.email %></td>
                  <td><%= user.username %></td>
                  <td><%= user.fullname %></td>
                  <td><%= user.role.name %></td>
                  <td>
                  <%= link_to 'Xem', user_path(user) %> /
                  <%= link_to 'Sửa', edit_user_path(user) %> /
                  <%= link_to 'Xóa', user_path(user),
                      method: :delete,
                      data: { confirm: 'Bạn có chắc không?' } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
        <div class="divider custom-divider"></div>
        <%= will_paginate @users %>
    </div>
</div>

tuphuong/app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Thêm người dùng</h2>
            <div class="row">
                <%= render 'form' %>
            </div>
            <a href="<%= users_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>

tuphuong/app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col s12">
            <h2 class="center-align">Tài khoản #<%= @user.id %></h2>
            <table>
                <thead>
                  <tr>
                      <th data-field="id">ID</th>
                      <th data-field="email">Email</th>
                      <th data-field="username">Tên đăng nhập</th>
                      <th data-field="fullname">Tên đầy đủ</th>
                      <th data-field="rold">Role</th>
                      <th data-field="action">Thao tác</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td><%= @user.id %></td>
                      <td><%= @user.email %></td>
                      <td><%= @user.username %></td>
                      <td><%= @user.fullname %></td>
                      <td><%= @user.role.name %></td>
                      <td>
                        <%= link_to 'Sửa', edit_user_path(@user) %> /
                        <%= link_to 'Xóa', user_path(@user),
                            method: :delete,
                            data: { confirm: 'Bạn có chắc không?' } %>
                      </td>
                    </tr>
                </tbody>
            </table>
            <a href="<%= users_path %>" class="waves-effect waves-light btn grey darken-3">
              <i class="mdi-hardware-keyboard-backspace"></i>
            </a>
        </div>
    </div>
</div>